spring.application.name=email-service

spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.username=joaog4030@gmail.com
spring.mail.password=ilmfhiwgebgaszvz

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

# RESOLUÇÃO DO ERRO 501:
spring.mail.properties.mail.smtp.localhost=localhost

# Opcional: mantenha o debug apenas se precisar testar mais
spring.mail.properties.mail.debug=true